version = 3.7.15
runner.dialect = scala3

newlines.selectChains = fold
maxColumn = 120
align.preset = some
align.tokens.add = [
  { code = ":=", owners = [{ regex = ".*" }] }
  { code = "<>", owners = [{ regex = ".*" }] }
  { code = "=",  owners = [{ regex = ".*" }] }
]
